[repository]
name = "intranet-v2tec"
changelog = "CHANGELOG.md"
version = "version.txt"
version_format = "calver"
container_images_prefix = "ghcr.io/soaresmpd/intranet-v2tec-"
compose = ["docker-compose.yml"]

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend.package]
name = "v2tec.intranet"
path = "backend"
code_path = "src/v2tec/intranet"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "Products.CMFPlone"
publish = false

[frontend.package]
name = "volto-v2tec-intranet"
path = "frontend/packages/volto-v2tec-intranet"
code_path = "src"
changelog = "frontend/packages/volto-v2tec-intranet/CHANGELOG.md"
towncrier_settings = "frontend/packages/volto-v2tec-intranet/towncrier.toml"
base_package = "@plone/volto"
publish = false

[cookieplone]
template = "project"
template_version = "cda10db886223a9aa9be1b1368484296418bb880"
generated_date = "2026-05-28 17:12:48"
